site_name: Panconvert Documentation
site_url: http://panconvert.readthedocs.org
pages:
- ['index.md', 'Introduction']
- ['User-Guide/Basic_Info.md', 'User Guide', 'Basic Information']
- ['User_Guide/Basic_Usage.md', 'User Guide', 'Basic Usage']
- ['User_Guide/U
pdate.md', 'User Guide', 'Update']